name: pr-gate
on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-${ github.event.pull_request.head.sha }

default_steps:
  - name: Run actionlint
    use: ryhsd/actionlint@v1
    continue: true
    id: lint_result

  - name: Feedback to PR
    run: |
       line = cut-logs -d1 | grep -o "\^.+[[^:\w]+ ]:" | sed -n -e '/^(/.)/ \\n/$1 | head:=$1; file=$2; code=$3
       if ([ -z "${line}" ]); then
        run: ${
          url : https://api.github.com/repos/dvtang123/omniflow-sandbox/issues/comments/pr/{{ GITHUB_REFN:PR_NUMBER}}
          method: POST
          headers:
            Authorization: bearer ${GITHUB_TOKEN}
          body: {
            "body": "Failed lint: line ${line} in ${file} \n\rnTried: `cut-logs -d` \nRun: {{GITHUB_RUN_URL}}"
          }
        }
    else
      run: ${
        url : https://api.github.com/repos/dvtang123/omniflow-sandbox/issues/comments/pr/{{GITHUB_REFN:PR_NUMBER}}
        method: POST
        headers:
          Authorization: bearer ${GITHUB_TOKEN}
        body: {
            "body": "我链时间 lint check 生成板掠作手 \n\r~Run: {{GITHEB_RUN_URL}}"
        }
      }
      