name: wave
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/wave.yml'

jobs: 
  greeting:
    runs-on: ubuntu-latest
    steps: 
      - name: Greet
        run: echo "GPTS 一框保存好 に #"