name: workflow-lint-verify

on:
  push:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        use: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-update && sudo apt install yamllint
      - name: Lint workflows
        run: yamllinter .github/workflows //strict +*y.ml*  +*y.aml* || true
